export const LOGIN_GALLERY = 'LOGIN_GALLERY'
export const SIGNUP_GALLERY = 'SIGNUP_GALLERY'
export const GALLERY = 'GALLERY'
export const EXHIBITIONS = 'EXHIBITIONS'
export const EXHIBITED_ARTWORKS = 'EXHIBITED_ARTWORKS'
export const GALLERY_ARTWORKS = 'GALLERY_ARTWORKS'
export const CREATE_NEW_EXHIBITION = "CREATE_NEW_EXHIBITION"
export const DELETE_EXHIBITION = "DELETE_EXHIBITION"